// AUTO-GENERATED by scripts/inject-ask-context.sh — do not edit directly.
// Authoritative sources:
//   context/insurance/ask-schema-prompt.txt
//   context/insurance/ask-business-prompt.txt

export const SCHEMA_KNOWLEDGE = `
## BigQuery Tables — USE THESE EXACT TABLE NAMES (backtick-quoted)

### \`hx-data-production.insurance.insurance_trading_data\`
The ONLY policy table. Every row = one transaction event on a policy.
CRITICAL RULES:
- ALWAYS use the full name: \`hx-data-production.insurance.insurance_trading_data\`
- Use SUM(policy_count) not COUNT(*) for policy counts — multiple rows per policy
- Use SUM(CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)) for Post PPC GP — NEVER AVG()
- Avg GP = SUM(CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)) / NULLIF(SUM(policy_count), 0)
- All BIGNUMERIC columns must be CAST to FLOAT64 for aggregation
- YoY = 364-day offset (matches day-of-week)
- looker_trans_date is DATETIME type — use DATE(looker_trans_date) for comparisons

TRANSACTION MODEL (version column):
- version 1 = New Issue (policy_count = 1)
- version 2 = Contra/reversal (policy_count = -1)
- version 3 = Cancellation (always paired with a Contra)
- version 4 = MTA/Amendment (always paired with a Contra)
SUM(policy_count) correctly nets these out. transaction_type has: New Issue, Contra, MTA Debit, Cancellation.

DATE COLUMNS: looker_trans_date (DATETIME, primary — use DATE() for comparisons), transaction_datetime, looker_start_date, looker_end_date (policy expiry — for renewal calcs), duration (days, 365=annual), issue_date, quote_date, cancellation_date.

PRODUCT COLUMNS: policy_type (Annual/Single), scheme_name (e.g. "Bronze Main Single Med HX" — encodes cover+type+med+brand), scheme_id, scheme_version, product (e.g. "Direct Travel", "Direct Cruise"), cover_level_name (Bronze/Silver/Gold), cover_level_tier (1/2/3), brand.

DISTRIBUTION COLUMNS:
- distribution_channel: Direct, Aggregator, Partner Referral, Renewals (primary split)
- channel: more specific e.g. "Direct - Standard", "Direct - Medical", "Partner Referral - Standard"
- insurance_group: sub-channel e.g. "Cross Sell", "Direct Mailings", "Affiliates", "Independent", "Web Links"
- agent_code, agent_name, agent_group: attribution (e.g. "AH760"/"AIRLINE CC REF"/"I9", "AW660"/"APS-BKSLON-16"/"MO")
- campaign_name: e.g. "DIR-CRU-REN-Direct", "DIR-Direct", "REF-Referral"
- booking_source: Web, Contact Centre, Auto Renewal
- transaction_source: Web, Contact Centre, Auto Renewal

CUSTOMER COLUMNS: customer_id (UUID), customer_type (New/Existing/Lapsed/Re-engaged), customer_type_insurance_only, max_age_at_purchase, residence, lead_postcode, customer_area, customer_region, lead_dob, highest_dob.

TRAVELLER COLUMNS: pax (total passengers), adults, children, family_group (Couple/Individual/Family).

DESTINATION COLUMNS: destination_full, destination (Europe Inc/Worldwide Exc), destination_group (Europe/Worldwide), highest_rated_country.

MEDICAL COLUMNS: medical_split (Medical/Non-Medical), max_medical_score, max_medical_score_grouped (0/2/3/4), has_undiagnosed_condition (BOOL), screened_pax.

KEY FINANCIAL COLUMNS:
- total_gross_inc_ipt: customer price (inc IPT)
- total_gross_exc_ipt_ntu_comm: Pre-PPC GP (price - IPT - underwriter - commission). Post PPC GP = CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)
- ppc_cost_per_policy: PPC cost allocated per policy (deduct from GP for Post PPC GP)
- est_13m_ins_gp: Estimated future insurance GP from this customer over 13 months (NULL if not new customer). COALESCE to 0.
- est_13m_other_gp: Estimated future non-insurance HX GP from this customer over 13 months (NULL if not new customer). COALESCE to 0.
- Total 13-month customer value = Post PPC GP + COALESCE(est_13m_ins_gp, 0) + COALESCE(est_13m_other_gp, 0). Only meaningful for new customers (customer_type='New'). Use when evaluating negative-margin strategies.
- total_paid_commission_value: commission paid to partner
- total_net_to_underwriter_inc_gadget: underwriter cost
- total_discount_value: discount applied (FLOAT64, not BIGNUMERIC)
- campaign_discount_perc: discount % (e.g. 15, 20, 24)
- ipt_rate: IPT rate
Financial decomposition: base_* (core policy), medical_* (screening), option_* (add-ons). Each has _gross_inc_ipt, _gross_exc_ipt, _ntu, _commission, _ntu_comm variants. *_exc_gadget_* = excluding gadget cover.

POLICY STATUS: policy_count (signed: +1 new/amend, -1 contra/cancel — ALWAYS SUM this), policy_status (Live/Cancelled), policy_renewal_year (0=new, 2+=renewal), auto_renew_opt_in (BOOL), underwriter (e.g. "ERGO").

### \`hx-data-production.commercial_finance.insurance_web_utm_4\`
Web analytics — event-level. Direct channel ONLY (no aggregator/renewal data).
Sessions = COUNT(DISTINCT session_id). Users = COUNT(DISTINCT visitor_id).
certificate_id is STRING here (INT64 in policies) — CAST for joins.

SESSION COLUMNS: session_id, visitor_id, session_seconds, session_start_date (DATE — primary filter), session_landing_path, session_landing_agent, session_browser_name.

PAGE/EVENT COLUMNS: device_type (mobile/computer/tablet), page_type (landing/gatekeeper/screening/extra_details/search_results/addon_results/checkout_*/just_booked), page_path, event_name (e.g. select_product, chat_started, verisk-radio-answer-*), event_type (click/auto_capture/customer_state/focus/capture/ecommerce), event_value, booking_flow_stage (funnel stage).

MEASURING SEARCH TRAFFIC: Use page_type = 'search_results' to count sessions reaching the quote page. Do NOT use event_name = 'engine_search_button'.

FIELD AVAILABILITY BY FUNNEL STAGE: Before search_results, only device_type/distribution_channel/insurance_group/customer_type are available. policy_type and scheme fields only populate AT search_results. cover_level only populates AFTER search_results. Max granularity for session-to-search: distribution_channel → insurance_group → customer_type → device_type. Do NOT break session-to-search by policy_type or cover_level — they are not known yet.

PRODUCT COLUMNS: scheme_search (Single/Annual — search intent, only at search_results+), insurance_group (sub-channel: "Web Links", "Direct Mailings", "Affiliates" — SAME dimension as policies table, available from landing), scheme_name, scheme_type, scheme_id.

DESTINATION: region_name, travel_start_date, travel_end_date, duration, passenger_count.

FINANCIAL (per certificate): certificate_gross, certificate_ipt, certificate_nett, certificate_margin, total_gross, total_gp, policy_screening_gross, policy_screening_margin.

MARKETING: campaign, source, medium, channel (UTM channel), utm_id.

FLAGS: Multiple_search (STRING: "Yes"/"No"), med_session (BOOL), used_syd (BOOL), customer_type (New/Existing/Lapsed/Re-engaged).

### Joining the tables (CRITICAL — read carefully)
The ONLY safe join key: CAST(p.certificate_id AS STRING) = w.certificate_id
Web table = Direct channel only. No web data for aggregator/renewal.

Fields that exist in BOTH tables (safe to use in cross-table queries):
- certificate_id (STRING in web, INT64 in trading — CAST for joins)
- insurance_group (sub-channel: "Cross Sell", "Direct Mailings", "Web Links", etc.)
- customer_type (New/Existing/Lapsed/Re-engaged)
- device_type (web table only has this for sessions; trading table does NOT have device_type)

Fields ONLY in the web table (NOT in trading): session_id, visitor_id, page_type, event_name, event_type, booking_flow_stage, scheme_search, med_session, Multiple_search, session_start_date
Fields ONLY in the trading table (NOT in web): distribution_channel, policy_type, cover_level_name, total_gross_exc_ipt_ntu_comm, policy_count, looker_trans_date, ppc_cost_per_policy

When calculating conversion rates (e.g. session-to-book):
- Get sessions from the WEB table and bookings from the TRADING table SEPARATELY
- Aggregate each independently, then divide — do NOT join row-level then count
- Example: sessions = COUNT(DISTINCT session_id) from web WHERE session_start_date BETWEEN ...
  bookings = SUM(policy_count) from trading WHERE DATE(looker_trans_date) BETWEEN ... AND distribution_channel = 'Direct'
  conversion = bookings / sessions

SANITY CHECK: Conversion rates can NEVER exceed 100%. If your result shows >100%, the query is wrong — likely joining on a field that doesn't exist in both tables, causing row multiplication. Fix the query.

### insurance_group (both tables)
Sub-channel within distribution channels: "Cross Sell", "Direct Mailings", "Web Links", "Affiliates", "Independent". Use this for drilling into which sub-channel drives patterns within Direct/Partner Referral.

### customer_type (both tables)
New = first time with HX. Existing = booked in last 3 years. Lapsed = no booking in 3+ years. Re-engaged = returned after lapse.
`;

export const BUSINESS_CONTEXT = `
- HX runs NEGATIVE margins on annual policies deliberately (lifetime value strategy). Never flag as problem.
- Single trip losses ARE problems — no renewal pathway.
- Traffic x Conversion x Avg GP = Total GP. Always decompose.
- Aggregators have no web journey data. Direct has full web data.
- Use SUM(policy_count) for counts. Use SUM(CAST(col AS FLOAT64))/NULLIF(SUM(policy_count),0) for averages.
- YoY comparison = 364-day offset to match day-of-week.
- Financial Year To Date (FYTD) runs 1 April to 31 March. "YTD" or "FYTD" means from 1 April of the current financial year.
- RENEWAL RATE & VOLUME — two drivers: (1) how many policies are expiring, (2) the renewal rate.
  Expiring policies = Annual policies (policy_type='Annual', ANY distribution channel) where looker_end_date falls in the period.
  Renewal policies = policies where distribution_channel='Renewals' with DATE(looker_trans_date) in the period.
  Renewal rate = renewed / expiring, joined on looker_end_date = DATE(looker_trans_date).
  CRITICAL: Renewal rate can ONLY be calculated at a BLENDED level (all channels combined).
  There is NO column linking a renewal back to the original expiry channel, so you CANNOT
  calculate per-channel renewal rates. NEVER join renewals to expiries broken out by channel —
  this DUPLICATES the renewal count across every channel row, producing nonsensical rates.
  The expiry CHANNEL BREAKDOWN is useful ONLY for understanding the MIX of expiring policies
  (volume and proportion by channel). The mix matters because different channels have different
  typical renewal rates, so a shift in the expiry mix changes the blended rate even if
  underlying renewal behaviour is unchanged.
  ALSO consider GP: the GP of expiring policies affects the GP of renewals.
  If high-GP channels (e.g. Direct) make up more of the expiry mix, renewed GP will be higher
  even at the same renewal rate. Conversely, if low-GP channels dominate expiries, renewed GP
  drops. Always include GP in the expiry mix query to show this effect.
  CORRECT approach — use TWO SEPARATE queries:
  Query 1 — Blended renewal rate + GP:
    WITH expiry_pols AS (
      SELECT looker_end_date AS expiry_date, SUM(policy_count) AS expiring,
             SUM(CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)) AS expiring_gp
      FROM \`hx-data-production.insurance.insurance_trading_data\`
      WHERE looker_end_date BETWEEN @start AND @end AND LOWER(policy_type) = LOWER('Annual')
      GROUP BY looker_end_date
    ),
    renewal_pols AS (
      SELECT DATE(looker_trans_date) AS transaction_date, SUM(policy_count) AS renewed,
             SUM(CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)) AS renewed_gp
      FROM \`hx-data-production.insurance.insurance_trading_data\`
      WHERE DATE(looker_trans_date) BETWEEN @start AND @end AND LOWER(distribution_channel) = LOWER('Renewals')
      GROUP BY DATE(looker_trans_date)
    )
    SELECT e.expiry_date, e.expiring, e.expiring_gp,
           COALESCE(r.renewed,0) AS renewed, COALESCE(r.renewed_gp,0) AS renewed_gp,
           SAFE_DIVIDE(COALESCE(r.renewed,0), e.expiring) AS renewal_rate,
           SAFE_DIVIDE(e.expiring_gp, e.expiring) AS avg_expiry_gp,
           SAFE_DIVIDE(COALESCE(r.renewed_gp,0), NULLIF(COALESCE(r.renewed,0),0)) AS avg_renewed_gp
    FROM expiry_pols e LEFT JOIN renewal_pols r ON e.expiry_date = r.transaction_date
  Note: looker_end_date replaces travel_end_date, DATE(looker_trans_date) replaces transaction_date.
  Query 2 — Expiry mix breakdown with GP (to explain rate AND GP movements):
    SELECT distribution_channel AS expiry_channel,
           SUM(policy_count) AS expiring_policies,
           SUM(CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)) AS expiring_gp,
           SAFE_DIVIDE(SUM(CAST(total_gross_exc_ipt_ntu_comm AS FLOAT64) - COALESCE(CAST(ppc_cost_per_policy AS FLOAT64), 0)), NULLIF(SUM(policy_count),0)) AS avg_gp_per_policy
    FROM \`hx-data-production.insurance.insurance_trading_data\`
    WHERE looker_end_date BETWEEN @start AND @end AND LOWER(policy_type) = LOWER('Annual')
    GROUP BY distribution_channel
    ORDER BY expiring_policies DESC
`;
