#!/bin/bash
# Inject schema and business context into ask.js at deploy time.
# Reads from context/insurance/ prompt files, writes generated JS module.
#
# Usage: bash scripts/inject-ask-context.sh [domain]
# Default domain: insurance

set -euo pipefail

DOMAIN="${1:-insurance}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

SCHEMA_FILE="$PROJECT_DIR/context/$DOMAIN/ask-schema-prompt.txt"
BUSINESS_FILE="$PROJECT_DIR/context/$DOMAIN/ask-business-prompt.txt"
OUTPUT_FILE="$PROJECT_DIR/functions/api/_generated-context.js"

if [ ! -f "$SCHEMA_FILE" ]; then
  echo "ERROR: Schema prompt not found: $SCHEMA_FILE" >&2
  exit 1
fi

if [ ! -f "$BUSINESS_FILE" ]; then
  echo "ERROR: Business prompt not found: $BUSINESS_FILE" >&2
  exit 1
fi

# Read contents, escaping backticks for JS template literals
SCHEMA=$(sed 's/`/\\`/g' "$SCHEMA_FILE")
BUSINESS=$(sed 's/`/\\`/g' "$BUSINESS_FILE")

cat > "$OUTPUT_FILE" << JSEOF
// AUTO-GENERATED by scripts/inject-ask-context.sh — do not edit directly.
// Authoritative sources:
//   context/$DOMAIN/ask-schema-prompt.txt
//   context/$DOMAIN/ask-business-prompt.txt

export const SCHEMA_KNOWLEDGE = \`
${SCHEMA}
\`;

export const BUSINESS_CONTEXT = \`
${BUSINESS}
\`;
JSEOF

echo "Injected $DOMAIN context into $OUTPUT_FILE"
